INSERT INTO subject VALUES(DEFAULT, 'Africana Studies', 'AFRS');
INSERT INTO subject VALUES(DEFAULT, 'Asian & Asian American Studies', 'AAAS');
INSERT INTO subject VALUES(DEFAULT, 'Chicano & Latino Studies', 'CHLS');
INSERT INTO subject VALUES(DEFAULT, 'Child Developmnt & Family Stds', 'CDFS');
INSERT INTO subject VALUES(DEFAULT, 'Classics', 'CLSC');
INSERT INTO subject VALUES(DEFAULT, 'Communication Studies', 'COMM');
INSERT INTO subject VALUES(DEFAULT, 'Comparative World Literature', 'CWL');
INSERT INTO subject VALUES(DEFAULT, 'Computer Engr & Computer Sci', 'CECS');
INSERT INTO subject VALUES(DEFAULT, 'Concurrent Enrollment', 'XYZ');
INSERT INTO subject VALUES(DEFAULT, 'Consumer Affairs', 'CAFF');
INSERT INTO subject VALUES(DEFAULT, 'Counseling', 'COUN');
INSERT INTO subject VALUES(DEFAULT, 'Criminal Justice', 'CRJU');
INSERT INTO subject VALUES(DEFAULT, 'Dance', 'DANC');
INSERT INTO subject VALUES(DEFAULT, 'Education - Early Childhood', 'EDEC');
INSERT INTO subject VALUES(DEFAULT, 'Education - Elementary', 'EDEL');
INSERT INTO subject VALUES(DEFAULT, 'Education - Reading', 'EDRG');
INSERT INTO subject VALUES(DEFAULT, 'Education Specialist', 'EDSP');
INSERT INTO subject VALUES(DEFAULT, 'Educational Psychology', 'ED P');
INSERT INTO subject VALUES(DEFAULT, 'Electrical Engineering', 'E E');
INSERT INTO subject VALUES(DEFAULT, 'English', 'ENGL');
INSERT INTO subject VALUES(DEFAULT, 'Family & Consumer Sciences', 'FCS');
INSERT INTO subject VALUES(DEFAULT, 'Finance', 'FIN');
INSERT INTO subject VALUES(DEFAULT, 'French', 'FREN');
INSERT INTO subject VALUES(DEFAULT, 'Geographic Information Science', 'GISC');
INSERT INTO subject VALUES(DEFAULT, 'Geography', 'GEOG');
INSERT INTO subject VALUES(DEFAULT, 'Geology', 'GEOL');
INSERT INTO subject VALUES(DEFAULT, 'German', 'GERM');
INSERT INTO subject VALUES(DEFAULT, 'Gerontology', 'GERN');
INSERT INTO subject VALUES(DEFAULT, 'Graduate Studies', 'G S');
INSERT INTO subject VALUES(DEFAULT, 'Health Care Administration', 'HCA');
INSERT INTO subject VALUES(DEFAULT, 'Health Science', 'H SC');
INSERT INTO subject VALUES(DEFAULT, 'History', 'HIST');
INSERT INTO subject VALUES(DEFAULT, 'Hospitality Management', 'HFHM');
INSERT INTO subject VALUES(DEFAULT, 'Information Systems', 'I S');
INSERT INTO subject VALUES(DEFAULT, 'International Studies', 'I/ST');
INSERT INTO subject VALUES(DEFAULT, 'Italian', 'ITAL');
INSERT INTO subject VALUES(DEFAULT, 'Journalism', 'JOUR');
INSERT INTO subject VALUES(DEFAULT, 'Kinesiology', 'KIN');
INSERT INTO subject VALUES(DEFAULT, 'Liberal Studies', 'L/ST');
INSERT INTO subject VALUES(DEFAULT, 'Management', 'MGMT');
INSERT INTO subject VALUES(DEFAULT, 'Mathematics', 'MATH');
INSERT INTO subject VALUES(DEFAULT, 'Mathematics Prebaccalaureate', 'MAPB');
INSERT INTO subject VALUES(DEFAULT, 'Music', 'MUS');
INSERT INTO subject VALUES(DEFAULT, 'Nutrition and Dietetics', 'NUTR');
INSERT INTO subject VALUES(DEFAULT, 'Philosophy', 'PHIL');
INSERT INTO subject VALUES(DEFAULT, 'Physics', 'PHYS');
INSERT INTO subject VALUES(DEFAULT, 'Political Science', 'POSC');
INSERT INTO subject VALUES(DEFAULT, 'Psychology', 'PSY');
INSERT INTO subject VALUES(DEFAULT, 'Public Policy & Administration', 'PPA');
INSERT INTO subject VALUES(DEFAULT, 'Recreation', 'REC');
INSERT INTO subject VALUES(DEFAULT, 'Religious Studies', 'R/ST');
INSERT INTO subject VALUES(DEFAULT, 'Sociology', 'SOC');
INSERT INTO subject VALUES(DEFAULT, 'Spanish', 'SPAN');
INSERT INTO subject VALUES(DEFAULT, 'Statistics', 'STAT');
INSERT INTO subject VALUES(DEFAULT, 'Theatre Arts', 'THEA');
INSERT INTO subject VALUES(DEFAULT, 'University', 'UNIV');
INSERT INTO subject VALUES(DEFAULT, 'Womens Gender Sexuality Stds', 'WGSS');
