I, NOW(), NOW()NSERT INTO subjects VALUES(DEFAULT, 'Africana Studies', 'AFRS', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Asian & Asian American Studies', 'AAAS', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Chicano & Latino Studies', 'CHLS', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Child Developmnt & Family Stds', 'CDFS', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Classics', 'CLSC', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Communication Studies', 'COMM', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Comparative World Literature', 'CWL', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Computer Engr & Computer Sci', 'CECS', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Concurrent Enrollment', 'XYZ', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Consumer Affairs', 'CAFF', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Counseling', 'COUN', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Criminal Justice', 'CRJU', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Dance', 'DANC', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Education - Early Childhood', 'EDEC', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Education - Elementary', 'EDEL', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Education - Reading', 'EDRG', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Education Specialist', 'EDSP', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Educational Psychology', 'ED P', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Electrical Engineering', 'E E', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'English', 'ENGL', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Family & Consumer Sciences', 'FCS', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Finance', 'FIN', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'French', 'FREN', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Geographic Information Science', 'GISC', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Geography', 'GEOG', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Geology', 'GEOL', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'German', 'GERM', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Gerontology', 'GERN', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Graduate Studies', 'G S', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Health Care Administration', 'HCA', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Health Science', 'H SC', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'History', 'HIST', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Hospitality Management', 'HFHM', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Information Systems', 'I S', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'International Studies', 'I/ST', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Italian', 'ITAL', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Journalism', 'JOUR', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Kinesiology', 'KIN', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Liberal Studies', 'L/ST', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Management', 'MGMT', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Mathematics', 'MATH', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Mathematics Prebaccalaureate', 'MAPB', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Music', 'MUS', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Nutrition and Dietetics', 'NUTR', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Philosophy', 'PHIL', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Physics', 'PHYS', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Political Science', 'POSC', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Psychology', 'PSY', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Public Policy & Administration', 'PPA', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Recreation', 'REC', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Religious Studies', 'R/ST', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Sociology', 'SOC', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Spanish', 'SPAN', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Statistics', 'STAT', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Theatre Arts', 'THEA', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'University', 'UNIV', NOW(), NOW());
INSERT INTO subjects VALUES(DEFAULT, 'Womens Gender Sexuality Stds', 'WGSS');
